spring:
  cloud:
    nacos:
      config:
#        server-addr: 120.79.212.252:8848
#        namespace: 5ec6911b-fc1b-4055-b19e-8eec500d3d06
#        group: MY-GROUP
#        file-extension: yml
#        prefix: ${spring.application.name}
#      discovery:
#        server-addr: 120.79.212.252:8848
#        namespace: 5ec6911b-fc1b-4055-b19e-8eec500d3d06
#        group: MY-GROUP

        server-addr: localhost:8848
        namespace: 5ec6911b-fc1b-4055-b19e-8eec500d3d06
        group: MY-GROUP
        file-extension: yml
        prefix: ${spring.application.name}
      discovery:
        server-addr: localhost:8848
        namespace: 5ec6911b-fc1b-4055-b19e-8eec500d3d06
        group: MY-GROUP